# Generated by Django 3.0 on 2020-08-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Header', models.CharField(max_length=150)),
                ('Item', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
    ]
