# Generated by Django 3.0 on 2020-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
